<a href="https://colab.research.google.com/github/JOBIN-SABU/JOBIN-SABU/blob/main/Numpy_practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
df = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
df1 = np.random.normal(loc=0,scale=1,size=100)
print(df1)

[-0.21589577  0.63441719  0.49829514  0.84930181  0.49797941  1.75402325
  1.95485894 -0.54026696 -0.05461033 -3.28735334  0.18332579 -0.84040984
 -0.1435619  -1.12372826 -1.44442437  0.1929291  -0.57873359  0.20406606
  0.4538357   1.51962899 -0.9418274  -0.44596059 -0.6334736  -0.99288591
 -1.50639867 -0.17471633 -0.23399253  1.76102887  1.07087378  1.0000467
 -1.27197819 -1.97268879 -2.13076743 -0.03626727 -0.8940989   0.38063336
  1.79408577  0.77311351  1.5099572  -1.33007706 -0.24542917  1.0575942
 -0.33855749 -0.69401484  0.25902108  1.2240253   3.15930432  0.54343209
  0.71344621 -0.17431102 -0.77032201 -0.58652085  0.16190605  0.05579404
 -0.54976072  0.44343962  0.98189813 -0.61857708  1.45755214  2.10004877
  0.27741107 -0.77391043 -0.42256001 -0.68369055 -1.49452671 -1.1937536
 -0.42331534  0.02155643  1.42015718 -0.22053519 -1.8578336  -0.19825395
 -0.09962783 -0.65874333  1.21416236  1.0843218  -0.60640344  2.0866984
  0.6899923   0.05738163 -0.16573936 -1.6762696   1.082

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
for i in range(len(arr)):
    if i % 2 != 0:
        arr[i] = -arr[i]
print(arr)

[ 1 -2  3 -4  5 -6  7 -8  9]


In [ ]:
def convert_odd_index_to_neg(arr):
    # Create a list with elements changed based on index
    modified_list = [np.mean(arr) if x > np.mean(arr) else x for i, x in enumerate(arr)]
    # Convert the modified list back to a numpy array before returning
    return np.array(modified_list)
    # Test the function with the example array
arr = np.array([1,2,3,4,5,6,7,8,9])
print(convert_odd_index_to_neg(arr))

[1. 2. 3. 4. 5. 5. 5. 5. 5.]


In [ ]:
ar = np.arange(10)
print(ar)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
def normalization(arr,highest_value,lowest_value):
  normalized_value = (arr - lowest_value) / (highest_value - lowest_value)
  return normalized_value

In [ ]:
normalized_arr = normalization(ar,ar.max(),ar.min())
print(normalized_arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
import numpy as np
df = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
np.where(df == 8)

(array([2]), array([1]))

In [ ]:
def max_sum_row(matrix):
  rows_sums = np.sum(matrix , axis=1)
  max_sum_index = np.argmax(rows_sums)
  return matrix[max_sum_index]

In [ ]:
msum = max_sum_row(df)

In [ ]:
print(msum)

[7 8 9]


In [ ]:
import numpy as np

# Create a 3D array of shape (4, 4, 3) with random float values between 0 and 1
img = np.random.rand(4, 3, 3)

print(img)


[[[0.82488551 0.82398236 0.26758003]
  [0.07512759 0.56088842 0.30459469]
  [0.9508474  0.05491989 0.84839649]]

 [[0.30427827 0.00209492 0.80023487]
  [0.244914   0.21959459 0.38587836]
  [0.47710655 0.40563436 0.49771432]]

 [[0.5909903  0.83227998 0.84612542]
  [0.159813   0.87661215 0.15140853]
  [0.08676341 0.76637772 0.07207295]]

 [[0.69408453 0.98082233 0.18495051]
  [0.21625858 0.66409126 0.77769209]
  [0.40872894 0.66405454 0.82447419]]]


In [ ]:
import numpy as np

# Suppose 'img' is your 3D NumPy array of shape (height, width, channels)
# Example: img = np.random.rand(256, 256, 3)

# Flip vertically (top to bottom): reverse rows
vertical_flip = img[::-1, :, :]

# Flip horizontally (left to right): reverse columns
horizontal_flip = img[:, ::-1, :]

# Flip both vertically and horizontally
both_flipped = img[::-1, ::-1, :]

In [ ]:
vertical_flip

array([[[0.69408453, 0.98082233, 0.18495051],
        [0.21625858, 0.66409126, 0.77769209],
        [0.40872894, 0.66405454, 0.82447419]],

       [[0.5909903 , 0.83227998, 0.84612542],
        [0.159813  , 0.87661215, 0.15140853],
        [0.08676341, 0.76637772, 0.07207295]],

       [[0.30427827, 0.00209492, 0.80023487],
        [0.244914  , 0.21959459, 0.38587836],
        [0.47710655, 0.40563436, 0.49771432]],

       [[0.82488551, 0.82398236, 0.26758003],
        [0.07512759, 0.56088842, 0.30459469],
        [0.9508474 , 0.05491989, 0.84839649]]])

In [ ]:
horizontal_flip

array([[[0.9508474 , 0.05491989, 0.84839649],
        [0.07512759, 0.56088842, 0.30459469],
        [0.82488551, 0.82398236, 0.26758003]],

       [[0.47710655, 0.40563436, 0.49771432],
        [0.244914  , 0.21959459, 0.38587836],
        [0.30427827, 0.00209492, 0.80023487]],

       [[0.08676341, 0.76637772, 0.07207295],
        [0.159813  , 0.87661215, 0.15140853],
        [0.5909903 , 0.83227998, 0.84612542]],

       [[0.40872894, 0.66405454, 0.82447419],
        [0.21625858, 0.66409126, 0.77769209],
        [0.69408453, 0.98082233, 0.18495051]]])

In [ ]:

# Dot product of two 1-D arrays (vectors)
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
dot_product_vectors = np.dot(vector_a, vector_b)
print(f"Dot product of vectors: {dot_product_vectors}")

# Dot product (matrix multiplication) of two 2-D arrays (matrices)
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
dot_product_matrices = np.dot(matrix_a, matrix_b)
print(f"Dot product of matrices:\n{dot_product_matrices}")

Dot product of vectors: 32
Dot product of matrices:
[[19 22]
 [43 50]]


In [ ]:
def dot(A,B):
  return  np.sum(A*B)

In [ ]:
dot_product_matrices = dot(matrix_a, matrix_b)

In [ ]:
dot_product_vectors

np.int64(32)

In [ ]:
#Given X and W implement forward pass of neural layer: y = XW  + b
def forward_pass(X,W,b):
    y = np.dot(X,W)+b
    return y
X = np.array([[1, 2]])
W = np.array([[0.5, -1], [1.5, 2]])
b = np.array([0.1, -0.2])

# Output: (1×2) shape
print(forward_pass(X, W, b))


[[3.6 2.8]]


In [ ]:
#Compute cosine similarity betwen two vectors using only NumPy
def cosine_similarity(arr1,arr2):
  Xdot_product = np.dot(arr1, arr2)
  norm_a = np.linalg.norm(arr1)
  norm_b = np.linalg.norm(arr2)
  return dot_product / (norm_a * norm_b)

In [ ]:
import math
def calculate_frobenius_norm(matrix):
  sum_of_squares = 0
  for row in matrix:
    for element in row:
      sum_of_squares += element**2

  forbenius_norm = math.sqrt(sum_of_squares)
  return forbenius_norm

In [ ]:
print(calculate_frobenius_norm(df))

16.881943016134134


In [ ]:
df

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
df.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
#Implement a 2D convolution manually (no np.convolve, no loops).
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

def convolve2d_manual(image, kernel):
    kernel = np.flip(kernel, axis=(0, 1))
    patches = sliding_window_view(image, kernel.shape)
    return np.einsum('ijkl,kl->ij', patches, kernel)

In [ ]:
image = np.array([
    [1, 2, 3, 0],
    [0, 1, 2, 3],
    [3, 0, 1, 2],
    [2, 3, 0, 1]
])

kernel = np.array([
    [0, 1],
    [2, 3]
])

print(convolve2d_manual(image, kernel))


[[ 7 13 11]
 [ 5  7 13]
 [11  5  7]]


In [ ]:
#Write a function to compute softmax using only NumPy
import numpy as np

def softmax(x):
    x_shifted = x - np.max(x, axis=-1, keepdims=True)
    exp_x = np.exp(x_shifted)
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

In [ ]:
#Implement a sigmoid function and its derivatives.
def sigmoid_function(x):
  return 1/(1+np.exp(-x))
def sigmoid_derivative(x):
   s = sigmoid_function(x)
   return s*(1-s)